
# python -u ../main_frame_val_text_missing.py --dataset='CMU-MOSEI' --valid_dataset='CMU-MOSEI_valid' --test_dataset='CMU-MOSEI_test' --model='wengnet_mosei_mult_views_text_missing' --test_sets='test3'  --num_workers=4 --audio_feature='wavlm-large-FRA_-5' --text_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-gt' --video_feature='manet_FRA' --feat4_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-wav+prompt[take_generate_wordembed]' --batch_size=64 --lr=1e-4 --epochs=35 --gpu=3



python -u ../main_frame_val_text_missing.py --dataset='CMU-MOSEI' --valid_dataset='CMU-MOSEI_valid' --test_dataset='CMU-MOSEI_test' --model='wengnet_mosei_mult_views_text_missing' --test_sets='test3'  --num_workers=4 --audio_feature='wavlm-large-FRA_-5' --text_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-gt' --video_feature='manet_FRA' --feat4_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-wav+prompt[take_generate_wordembed_-4]' --batch_size=96 --lr=1e-4 --epochs=25 --gpu=0 --full_mse_loss_w=0.5 --missing_mse_loss_w=0.5 --text_feat_loss_w=0 --text_query_feat_loss_w=0 --features_loss_w=0.13 --rnc_loss_w=0.5


# python -u ../main_frame_val_text_missing.py --dataset='CMU-MOSEI' --valid_dataset='CMU-MOSEI_valid' --test_dataset='CMU-MOSEI_test' --model='wengnet_mosei_mult_views_text_missing' --test_sets='test3'  --num_workers=4 --audio_feature='wavlm-large-FRA_-5' --text_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-gt[-4_-1]' --video_feature='manet_FRA' --feat4_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-wav+prompt[take_generate_wordembed_-4]' --batch_size=128 --lr=1e-4 --epochs=25 --gpu=3 --full_mse_loss_w=0.5 --missing_mse_loss_w=0.5 --text_feat_loss_w=0.1 --text_query_feat_loss_w=0.7 --features_loss_w=0.13 --rnc_loss_w=0.5
# python -u ../main_frame_val_text_missing.py --dataset='CMU-MOSEI' --valid_dataset='CMU-MOSEI_valid' --test_dataset='CMU-MOSEI_test' --model='wengnet_mosei_mult_views_text_missing' --test_sets='test3'  --num_workers=4 --audio_feature='wavlm-large-FRA_-5' --text_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-gt[-4]' --video_feature='manet_FRA' --feat4_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-wav+prompt[take_generate_wordembed]' --batch_size=128 --lr=1e-4 --epochs=25 --gpu=3 --full_mse_loss_w=0.5 --missing_mse_loss_w=0.5 --text_feat_loss_w=0.1 --text_query_feat_loss_w=0.7 --features_loss_w=0.13 --rnc_loss_w=0.5
# python -u ../main_frame_val_text_missing.py --dataset='CMU-MOSEI' --valid_dataset='CMU-MOSEI_valid' --test_dataset='CMU-MOSEI_test' --model='wengnet_mosei_mult_views_text_missing' --test_sets='test3'  --num_workers=4 --audio_feature='wavlm-large-FRA_-5' --text_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-gt[-4_-1]' --video_feature='manet_FRA' --feat4_feature='wavlm-large-FRA_-5' --batch_size=128 --lr=1e-4 --epochs=25 --gpu=3 --full_mse_loss_w=0.5 --missing_mse_loss_w=0.5 --text_feat_loss_w=0.1 --text_query_feat_loss_w=0.7 --features_loss_w=0.13 --rnc_loss_w=0.5

# python -u ../main_frame_val_text_missing.py --dataset='CMU-MOSEI' --valid_dataset='CMU-MOSEI_valid' --test_dataset='CMU-MOSEI_test' --model='wengnet_mosei_mult_views_text_missing' --test_sets='test3'  --num_workers=4 --audio_feature='wavlm-large-FRA_-5' --text_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-gt' --video_feature='manet_FRA' --feat4_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-wav+prompt[take_generate_wordembed]' --batch_size=128 --lr=1e-4 --epochs=25 --gpu=3 --text_feat_loss_w=0.1 --text_query_feat_loss_w=0.7 --features_loss_w=0.1 --rnc_loss_w=0.5
# python -u ../main_frame_val_text_missing.py --dataset='CMU-MOSEI' --valid_dataset='CMU-MOSEI_valid' --test_dataset='CMU-MOSEI_test' --model='wengnet_mosei_mult_views_text_missing' --test_sets='test3'  --num_workers=4 --audio_feature='wavlm-large-FRA_-5' --text_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-gt' --video_feature='manet_FRA' --feat4_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-wav+prompt[take_generate_wordembed]' --batch_size=128 --lr=1e-4 --epochs=25 --gpu=3 --text_feat_loss_w=0.1 --text_query_feat_loss_w=0.7 --features_loss_w=0.1 --rnc_loss_w=0.5
# python -u ../main_frame_val_text_missing.py --dataset='CMU-MOSEI' --valid_dataset='CMU-MOSEI_valid' --test_dataset='CMU-MOSEI_test' --model='wengnet_mosei_mult_views_text_missing' --test_sets='test3'  --num_workers=4 --audio_feature='wavlm-large-FRA_-5' --text_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-gt' --video_feature='manet_FRA' --feat4_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-wav+prompt[take_generate_wordembed]' --batch_size=128 --lr=1e-4 --epochs=25 --gpu=3 --text_feat_loss_w=0.1 --text_query_feat_loss_w=0.7 --features_loss_w=0.1 --rnc_loss_w=0.5
# python -u ../main_frame_val_text_missing.py --dataset='CMU-MOSEI' --valid_dataset='CMU-MOSEI_valid' --test_dataset='CMU-MOSEI_test' --model='wengnet_mosei_mult_views_text_missing' --test_sets='test3'  --num_workers=4 --audio_feature='wavlm-large-FRA_-5' --text_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-gt' --video_feature='manet_FRA' --feat4_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-wav+prompt[take_generate_wordembed]' --batch_size=128 --lr=1e-4 --epochs=25 --gpu=3 --text_feat_loss_w=0.1 --text_query_feat_loss_w=0.7 --features_loss_w=0.1 --rnc_loss_w=0.5
# python -u ../main_frame_val_text_missing.py --dataset='CMU-MOSEI' --valid_dataset='CMU-MOSEI_valid' --test_dataset='CMU-MOSEI_test' --model='wengnet_mosei_mult_views_text_missing' --test_sets='test3'  --num_workers=4 --audio_feature='wavlm-large-FRA_-5' --text_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-gt' --video_feature='manet_FRA' --feat4_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-wav+prompt[take_generate_wordembed]' --batch_size=128 --lr=1e-4 --epochs=25 --gpu=3 --text_feat_loss_w=0.1 --text_query_feat_loss_w=0.7 --features_loss_w=0.1 --rnc_loss_w=0.5
# python -u ../main_frame_val_text_missing.py --dataset='CMU-MOSEI' --valid_dataset='CMU-MOSEI_valid' --test_dataset='CMU-MOSEI_test' --model='wengnet_mosei_mult_views_text_missing' --test_sets='test3'  --num_workers=4 --audio_feature='wavlm-large-FRA_-5' --text_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-gt' --video_feature='manet_FRA' --feat4_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-wav+prompt[take_generate_wordembed]' --batch_size=128 --lr=1e-4 --epochs=25 --gpu=3 --text_feat_loss_w=0.1 --text_query_feat_loss_w=0.7 --features_loss_w=0.1 --rnc_loss_w=0.5

# python -u ../main_frame_val_text_missing.py --dataset='CMU-MOSEI' --valid_dataset='CMU-MOSEI_valid' --test_dataset='CMU-MOSEI_test' --model='wengnet_mosei_mult_views_text_missing' --test_sets='test3'  --num_workers=4 --audio_feature='wavlm-large-FRA_-5' --text_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-gt' --video_feature='manet_FRA' --feat4_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-wav+prompt[take_generate_wordembed]' --batch_size=64 --lr=1e-4 --epochs=26 --gpu=3 --text_feat_loss_w=0.1 --text_query_feat_loss_w=0.7 --features_loss_w=0.1 --rnc_loss_w=0
# python -u ../main_frame_val_text_missing.py --dataset='CMU-MOSEI' --valid_dataset='CMU-MOSEI_valid' --test_dataset='CMU-MOSEI_test' --model='wengnet_mosei_mult_views_text_missing' --test_sets='test3'  --num_workers=4 --audio_feature='wavlm-large-FRA_-5' --text_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-gt' --video_feature='manet_FRA' --feat4_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-wav+prompt[take_generate_wordembed]' --batch_size=64 --lr=1e-4 --epochs=26 --gpu=3 --text_feat_loss_w=0.1 --text_query_feat_loss_w=0.7 --features_loss_w=0 --rnc_loss_w=0.8
# python -u ../main_frame_val_text_missing.py --dataset='CMU-MOSEI' --valid_dataset='CMU-MOSEI_valid' --test_dataset='CMU-MOSEI_test' --model='wengnet_mosei_mult_views_text_missing' --test_sets='test3'  --num_workers=4 --audio_feature='wavlm-large-FRA_-5' --text_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-gt' --video_feature='manet_FRA' --feat4_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-wav+prompt[take_generate_wordembed]' --batch_size=64 --lr=1e-4 --epochs=26 --gpu=3 --text_feat_loss_w=0 --text_query_feat_loss_w=0 --features_loss_w=0.1 --rnc_loss_w=0.8
# python -u ../main_frame_val_text_missing.py --dataset='CMU-MOSEI' --valid_dataset='CMU-MOSEI_valid' --test_dataset='CMU-MOSEI_test' --model='wengnet_mosei_mult_views_text_missing' --test_sets='test3'  --num_workers=4 --audio_feature='wavlm-large-FRA_-5' --text_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-gt' --video_feature='manet_FRA' --feat4_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-wav+prompt[take_generate_wordembed]' --batch_size=64 --lr=1e-4 --epochs=26 --gpu=3 --text_feat_loss_w=0 --text_query_feat_loss_w=0.7 --features_loss_w=0.1 --rnc_loss_w=0.8
# python -u ../main_frame_val_text_missing.py --dataset='CMU-MOSEI' --valid_dataset='CMU-MOSEI_valid' --test_dataset='CMU-MOSEI_test' --model='wengnet_mosei_mult_views_text_missing' --test_sets='test3'  --num_workers=4 --audio_feature='wavlm-large-FRA_-5' --text_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-gt' --video_feature='manet_FRA' --feat4_feature='vicuna-7b-v1.5-FRA-wavlm2vicuna-half-wav+prompt[take_generate_wordembed]' --batch_size=64 --lr=1e-4 --epochs=26 --gpu=3 --text_feat_loss_w=0.1 --text_query_feat_loss_w=0 --features_loss_w=0.1 --rnc_loss_w=0.8

